# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

after_success:
    - Rscript -e 'covr::codecov(type = "all")'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'


